Дополняет верстку всех версий всех страниц
htmlacademy-adaptive/2122221-mishka-26 pull request #5
Opened 2022-08-26 15:18 UTC by annvolfers

2022-08-29 15:01 UTC, Dima-Dim requested changes
Помимо прочего, перепроверить форматирование scss файлов и убрать лишние символы.

2022-08-29 15:01 UTC, Dima-Dim commented on source/catalog.html
> +        <span class="main-nav__toggle-element"></span>
https://up.htmlacademy.ru/adaptive/26/criteries#d2

2022-08-29 15:01 UTC, Dima-Dim commented on source/catalog.html
>            <a class="main-nav__logo" href="index.html">
Кажется логотип всё же не является пунктом меню. Всё остальное тоже не факт что один однородный список, но может быть.

2022-08-29 15:01 UTC, Dima-Dim commented on source/js/script.js
> +let mainNav = document.querySelector('.main-nav');
Если переменная не переопределяется, то const.

2022-08-29 15:01 UTC, Dima-Dim commented on source/sass/blocks/about.scss
> +  & br {
https://up.htmlacademy.ru/adaptive/26/criteries#d11

2022-08-29 15:01 UTC, Dima-Dim commented on source/sass/blocks/control.scss
> +  .control:hover &,
Для чего в конце селектора `&`?

2022-08-29 15:01 UTC, Dima-Dim commented on source/sass/blocks/copyright.scss
> +  .copyright__link:hover &,
Здесь лишние пробелы, они сбивают с толку.

2022-08-29 18:32 UTC, annvolfers commented on source/catalog.html
> +        <span class="main-nav__toggle-element"></span>
поправила

2022-08-29 18:32 UTC, annvolfers commented on source/catalog.html
>            <a class="main-nav__logo" href="index.html">
спасибо, подумаю в эту сторону, это ведь сейчас не критично? боюсь не успеть защититься

2022-08-29 18:32 UTC, annvolfers commented on source/js/script.js
> +let mainNav = document.querySelector('.main-nav');
поправила

2022-08-29 18:32 UTC, annvolfers commented on source/sass/blocks/about.scss
> +  & br {
поправила

2022-08-29 18:37 UTC, annvolfers commented on source/sass/blocks/control.scss
> +  .control:hover &,
.control:hover .control__mark - при наведении на что-либо, что находится в теге label, меняется цвет бордера чекбокса. снова https://up.htmlacademy.ru/adaptive/26/criteries#d11 ?

2022-08-29 18:39 UTC, annvolfers commented on source/sass/blocks/copyright.scss
> +  .copyright__link:hover &,
что-то не вижу тут лишних пробелов и линтер не ругается. "Помимо прочего, перепроверить форматирование scss файлов и убрать лишние символы." - тут про это же? не нашла таких ошибок вообще..

2022-08-30 02:49 UTC, Dima-Dim commented on source/catalog.html
>            <a class="main-nav__logo" href="index.html">
Зависит от случайного проверяющего. насколько для него это критично :) Вообще просто логически не верно и верстать мы учимся тут именно для того, чтобы делать это правильно, а не пустыми спанами и абсолютами, как получится :)

2022-08-30 02:51 UTC, Dima-Dim commented on source/sass/blocks/copyright.scss
> +  .copyright__link:hover &,
Что за такой селектор `.copyright__link:hover &` для чего тут `&`? Кто и где учит так делать?

2022-08-30 09:48 UTC, annvolfers commented on source/catalog.html
>            <a class="main-nav__logo" href="index.html">
переделала, посмотрите пожалуйста

2022-08-30 09:48 UTC, annvolfers commented on source/sass/blocks/copyright.scss
> +  .copyright__link:hover &,
поправила, так лучше? если да, в остальных местах тоже поправлю

2022-08-30 10:29 UTC, Dima-Dim commented on source/sass/blocks/copyright.scss
> +  .copyright__link:hover &,
Да, так правильнее и читаемее, а ещё не нарушает критерий https://up.htmlacademy.ru/adaptive/26/criteries#d11
По этому это не лучше :) а правильнее :)

2022-08-30 11:09 UTC, annvolfers commented on source/sass/blocks/copyright.scss
> +  .copyright__link:hover &,
спасибо, поправила остальные

2022-08-31 15:49 UTC, merged